const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..', 'img', 'flow');

function scanDir(dirPath) {
  const result = {
    name: path.basename(dirPath),
    path: path.relative(path.join(__dirname, '..'), dirPath).replace(/\\/g, '/'),
    folders: [],
    files: []
  };

  const items = fs.readdirSync(dirPath, { withFileTypes: true });

  // Sort items numerically/alphabetically
  items.sort((a, b) => {
    return a.name.localeCompare(b.name, undefined, { numeric: true, sensitivity: 'base' });
  });

  for (const item of items) {
    const fullPath = path.join(dirPath, item.name);
    if (item.isDirectory()) {
      result.folders.push(scanDir(fullPath));
    } else if (item.isFile() && /\.(png|jpg|jpeg|gif|webp)$/i.test(item.name)) {
      result.files.push({
        name: item.name,
        path: path.relative(path.join(__dirname, '..'), fullPath).replace(/\\/g, '/')
      });
    }
  }

  return result;
}

try {
  const data = scanDir(rootDir);
  // Write to a JS file that exports a global variable `imgManifest`
  const code = `// Automatically generated by build_manifest.js\nconst imgManifest = ${JSON.stringify(data, null, 2)};\n`;
  fs.writeFileSync(path.join(__dirname, '..', 'img_data.js'), code, 'utf8');
  console.log('Manifest written to img_data.js successfully.');
} catch (err) {
  console.error('Error generating manifest:', err);
}
