// Automatically generated by build_manifest.js
const imgManifest = {
  "name": "flow",
  "path": "img/flow",
  "folders": [
    {
      "name": "1.FIrst Time login",
      "path": "img/flow/1.FIrst Time login",
      "folders": [],
      "files": [
        {
          "name": "1.jpg",
          "path": "img/flow/1.FIrst Time login/1.jpg"
        },
        {
          "name": "2.png",
          "path": "img/flow/1.FIrst Time login/2.png"
        },
        {
          "name": "3.png",
          "path": "img/flow/1.FIrst Time login/3.png"
        },
        {
          "name": "4.png",
          "path": "img/flow/1.FIrst Time login/4.png"
        },
        {
          "name": "5.png",
          "path": "img/flow/1.FIrst Time login/5.png"
        },
        {
          "name": "6.png",
          "path": "img/flow/1.FIrst Time login/6.png"
        },
        {
          "name": "7.png",
          "path": "img/flow/1.FIrst Time login/7.png"
        },
        {
          "name": "8.png",
          "path": "img/flow/1.FIrst Time login/8.png"
        },
        {
          "name": "9.png",
          "path": "img/flow/1.FIrst Time login/9.png"
        },
        {
          "name": "10.png",
          "path": "img/flow/1.FIrst Time login/10.png"
        },
        {
          "name": "11.png",
          "path": "img/flow/1.FIrst Time login/11.png"
        }
      ]
    },
    {
      "name": "2Dashboard",
      "path": "img/flow/2Dashboard",
      "folders": [],
      "files": [
        {
          "name": "1.png",
          "path": "img/flow/2Dashboard/1.png"
        },
        {
          "name": "2.png",
          "path": "img/flow/2Dashboard/2.png"
        },
        {
          "name": "3.png",
          "path": "img/flow/2Dashboard/3.png"
        },
        {
          "name": "4.png",
          "path": "img/flow/2Dashboard/4.png"
        },
        {
          "name": "5.png",
          "path": "img/flow/2Dashboard/5.png"
        },
        {
          "name": "6.png",
          "path": "img/flow/2Dashboard/6.png"
        },
        {
          "name": "7.png",
          "path": "img/flow/2Dashboard/7.png"
        }
      ]
    },
    {
      "name": "3Student",
      "path": "img/flow/3Student",
      "folders": [
        {
          "name": "1applications",
          "path": "img/flow/3Student/1applications",
          "folders": [],
          "files": [
            {
              "name": "1Students.png",
              "path": "img/flow/3Student/1applications/1Students.png"
            },
            {
              "name": "2Applications.png",
              "path": "img/flow/3Student/1applications/2Applications.png"
            },
            {
              "name": "3Applications.png",
              "path": "img/flow/3Student/1applications/3Applications.png"
            },
            {
              "name": "4Applications Details.png",
              "path": "img/flow/3Student/1applications/4Applications Details.png"
            },
            {
              "name": "5Applications.png",
              "path": "img/flow/3Student/1applications/5Applications.png"
            },
            {
              "name": "6Applications.png",
              "path": "img/flow/3Student/1applications/6Applications.png"
            },
            {
              "name": "7Applications.png",
              "path": "img/flow/3Student/1applications/7Applications.png"
            },
            {
              "name": "8Applications.png",
              "path": "img/flow/3Student/1applications/8Applications.png"
            },
            {
              "name": "9Applications.png",
              "path": "img/flow/3Student/1applications/9Applications.png"
            },
            {
              "name": "10Applications.png",
              "path": "img/flow/3Student/1applications/10Applications.png"
            },
            {
              "name": "11Add test scores.png",
              "path": "img/flow/3Student/1applications/11Add test scores.png"
            },
            {
              "name": "12Add test scores.png",
              "path": "img/flow/3Student/1applications/12Add test scores.png"
            },
            {
              "name": "13Add test scores.png",
              "path": "img/flow/3Student/1applications/13Add test scores.png"
            },
            {
              "name": "14Add test scores.png",
              "path": "img/flow/3Student/1applications/14Add test scores.png"
            },
            {
              "name": "15Add test scores.png",
              "path": "img/flow/3Student/1applications/15Add test scores.png"
            }
          ]
        },
        {
          "name": "2conversations",
          "path": "img/flow/3Student/2conversations",
          "folders": [],
          "files": [
            {
              "name": "1.png",
              "path": "img/flow/3Student/2conversations/1.png"
            },
            {
              "name": "2.png",
              "path": "img/flow/3Student/2conversations/2.png"
            },
            {
              "name": "3.png",
              "path": "img/flow/3Student/2conversations/3.png"
            },
            {
              "name": "4.png",
              "path": "img/flow/3Student/2conversations/4.png"
            },
            {
              "name": "5.png",
              "path": "img/flow/3Student/2conversations/5.png"
            },
            {
              "name": "6.png",
              "path": "img/flow/3Student/2conversations/6.png"
            },
            {
              "name": "7.png",
              "path": "img/flow/3Student/2conversations/7.png"
            },
            {
              "name": "8.png",
              "path": "img/flow/3Student/2conversations/8.png"
            },
            {
              "name": "9.png",
              "path": "img/flow/3Student/2conversations/9.png"
            },
            {
              "name": "10.png",
              "path": "img/flow/3Student/2conversations/10.png"
            },
            {
              "name": "11.png",
              "path": "img/flow/3Student/2conversations/11.png"
            },
            {
              "name": "12.png",
              "path": "img/flow/3Student/2conversations/12.png"
            },
            {
              "name": "13.png",
              "path": "img/flow/3Student/2conversations/13.png"
            },
            {
              "name": "14.png",
              "path": "img/flow/3Student/2conversations/14.png"
            }
          ]
        },
        {
          "name": "3comments",
          "path": "img/flow/3Student/3comments",
          "folders": [],
          "files": []
        }
      ],
      "files": [
        {
          "name": "1.png",
          "path": "img/flow/3Student/1.png"
        },
        {
          "name": "2.png",
          "path": "img/flow/3Student/2.png"
        },
        {
          "name": "3.png",
          "path": "img/flow/3Student/3.png"
        },
        {
          "name": "4.png",
          "path": "img/flow/3Student/4.png"
        },
        {
          "name": "5.png",
          "path": "img/flow/3Student/5.png"
        },
        {
          "name": "6.png",
          "path": "img/flow/3Student/6.png"
        },
        {
          "name": "7.png",
          "path": "img/flow/3Student/7.png"
        },
        {
          "name": "8.png",
          "path": "img/flow/3Student/8.png"
        },
        {
          "name": "9.png",
          "path": "img/flow/3Student/9.png"
        },
        {
          "name": "10.png",
          "path": "img/flow/3Student/10.png"
        },
        {
          "name": "11.png",
          "path": "img/flow/3Student/11.png"
        },
        {
          "name": "12.png",
          "path": "img/flow/3Student/12.png"
        },
        {
          "name": "13.png",
          "path": "img/flow/3Student/13.png"
        },
        {
          "name": "14.png",
          "path": "img/flow/3Student/14.png"
        },
        {
          "name": "15.png",
          "path": "img/flow/3Student/15.png"
        },
        {
          "name": "16.png",
          "path": "img/flow/3Student/16.png"
        },
        {
          "name": "17.png",
          "path": "img/flow/3Student/17.png"
        },
        {
          "name": "18.png",
          "path": "img/flow/3Student/18.png"
        },
        {
          "name": "19.png",
          "path": "img/flow/3Student/19.png"
        },
        {
          "name": "20.png",
          "path": "img/flow/3Student/20.png"
        },
        {
          "name": "21.png",
          "path": "img/flow/3Student/21.png"
        },
        {
          "name": "22.png",
          "path": "img/flow/3Student/22.png"
        },
        {
          "name": "23.png",
          "path": "img/flow/3Student/23.png"
        },
        {
          "name": "24.png",
          "path": "img/flow/3Student/24.png"
        },
        {
          "name": "25.png",
          "path": "img/flow/3Student/25.png"
        },
        {
          "name": "26.png",
          "path": "img/flow/3Student/26.png"
        },
        {
          "name": "27.png",
          "path": "img/flow/3Student/27.png"
        },
        {
          "name": "28.png",
          "path": "img/flow/3Student/28.png"
        },
        {
          "name": "29.png",
          "path": "img/flow/3Student/29.png"
        },
        {
          "name": "30.png",
          "path": "img/flow/3Student/30.png"
        },
        {
          "name": "31.png",
          "path": "img/flow/3Student/31.png"
        },
        {
          "name": "32.png",
          "path": "img/flow/3Student/32.png"
        },
        {
          "name": "33.png",
          "path": "img/flow/3Student/33.png"
        },
        {
          "name": "34.png",
          "path": "img/flow/3Student/34.png"
        },
        {
          "name": "35.png",
          "path": "img/flow/3Student/35.png"
        },
        {
          "name": "36.png",
          "path": "img/flow/3Student/36.png"
        }
      ]
    },
    {
      "name": "4Programs",
      "path": "img/flow/4Programs",
      "folders": [],
      "files": [
        {
          "name": "1.png",
          "path": "img/flow/4Programs/1.png"
        },
        {
          "name": "2.png",
          "path": "img/flow/4Programs/2.png"
        },
        {
          "name": "3.png",
          "path": "img/flow/4Programs/3.png"
        },
        {
          "name": "4.png",
          "path": "img/flow/4Programs/4.png"
        },
        {
          "name": "5.png",
          "path": "img/flow/4Programs/5.png"
        },
        {
          "name": "6.png",
          "path": "img/flow/4Programs/6.png"
        },
        {
          "name": "7.png",
          "path": "img/flow/4Programs/7.png"
        },
        {
          "name": "8.png",
          "path": "img/flow/4Programs/8.png"
        },
        {
          "name": "9.png",
          "path": "img/flow/4Programs/9.png"
        },
        {
          "name": "10.png",
          "path": "img/flow/4Programs/10.png"
        },
        {
          "name": "11.png",
          "path": "img/flow/4Programs/11.png"
        },
        {
          "name": "12.png",
          "path": "img/flow/4Programs/12.png"
        },
        {
          "name": "13.png",
          "path": "img/flow/4Programs/13.png"
        },
        {
          "name": "14.png",
          "path": "img/flow/4Programs/14.png"
        },
        {
          "name": "15.png",
          "path": "img/flow/4Programs/15.png"
        },
        {
          "name": "16.png",
          "path": "img/flow/4Programs/16.png"
        },
        {
          "name": "17.png",
          "path": "img/flow/4Programs/17.png"
        },
        {
          "name": "18.png",
          "path": "img/flow/4Programs/18.png"
        },
        {
          "name": "19.png",
          "path": "img/flow/4Programs/19.png"
        },
        {
          "name": "20.png",
          "path": "img/flow/4Programs/20.png"
        },
        {
          "name": "21.png",
          "path": "img/flow/4Programs/21.png"
        }
      ]
    },
    {
      "name": "5Calender",
      "path": "img/flow/5Calender",
      "folders": [],
      "files": [
        {
          "name": "Calender.png",
          "path": "img/flow/5Calender/Calender.png"
        }
      ]
    },
    {
      "name": "6Manage",
      "path": "img/flow/6Manage",
      "folders": [
        {
          "name": "bulkupload",
          "path": "img/flow/6Manage/bulkupload",
          "folders": [],
          "files": [
            {
              "name": "1.png",
              "path": "img/flow/6Manage/bulkupload/1.png"
            },
            {
              "name": "2.png",
              "path": "img/flow/6Manage/bulkupload/2.png"
            },
            {
              "name": "3.png",
              "path": "img/flow/6Manage/bulkupload/3.png"
            },
            {
              "name": "4.png",
              "path": "img/flow/6Manage/bulkupload/4.png"
            },
            {
              "name": "5.png",
              "path": "img/flow/6Manage/bulkupload/5.png"
            }
          ]
        },
        {
          "name": "invoice",
          "path": "img/flow/6Manage/invoice",
          "folders": [],
          "files": [
            {
              "name": "1.png",
              "path": "img/flow/6Manage/invoice/1.png"
            },
            {
              "name": "2.png",
              "path": "img/flow/6Manage/invoice/2.png"
            },
            {
              "name": "3.png",
              "path": "img/flow/6Manage/invoice/3.png"
            },
            {
              "name": "4.png",
              "path": "img/flow/6Manage/invoice/4.png"
            },
            {
              "name": "5.png",
              "path": "img/flow/6Manage/invoice/5.png"
            },
            {
              "name": "6.png",
              "path": "img/flow/6Manage/invoice/6.png"
            },
            {
              "name": "7.png",
              "path": "img/flow/6Manage/invoice/7.png"
            },
            {
              "name": "8.png",
              "path": "img/flow/6Manage/invoice/8.png"
            },
            {
              "name": "9.png",
              "path": "img/flow/6Manage/invoice/9.png"
            }
          ]
        },
        {
          "name": "learning",
          "path": "img/flow/6Manage/learning",
          "folders": [],
          "files": [
            {
              "name": "1.png",
              "path": "img/flow/6Manage/learning/1.png"
            },
            {
              "name": "2.png",
              "path": "img/flow/6Manage/learning/2.png"
            },
            {
              "name": "3.png",
              "path": "img/flow/6Manage/learning/3.png"
            }
          ]
        },
        {
          "name": "profile",
          "path": "img/flow/6Manage/profile",
          "folders": [],
          "files": [
            {
              "name": "1.png",
              "path": "img/flow/6Manage/profile/1.png"
            },
            {
              "name": "2.png",
              "path": "img/flow/6Manage/profile/2.png"
            },
            {
              "name": "3.png",
              "path": "img/flow/6Manage/profile/3.png"
            },
            {
              "name": "4.png",
              "path": "img/flow/6Manage/profile/4.png"
            },
            {
              "name": "5.png",
              "path": "img/flow/6Manage/profile/5.png"
            },
            {
              "name": "6.png",
              "path": "img/flow/6Manage/profile/6.png"
            },
            {
              "name": "7.png",
              "path": "img/flow/6Manage/profile/7.png"
            },
            {
              "name": "8.png",
              "path": "img/flow/6Manage/profile/8.png"
            },
            {
              "name": "9.png",
              "path": "img/flow/6Manage/profile/9.png"
            },
            {
              "name": "10.png",
              "path": "img/flow/6Manage/profile/10.png"
            },
            {
              "name": "11.png",
              "path": "img/flow/6Manage/profile/11.png"
            },
            {
              "name": "12.png",
              "path": "img/flow/6Manage/profile/12.png"
            }
          ]
        },
        {
          "name": "staff",
          "path": "img/flow/6Manage/staff",
          "folders": [],
          "files": [
            {
              "name": "1.png",
              "path": "img/flow/6Manage/staff/1.png"
            },
            {
              "name": "2.png",
              "path": "img/flow/6Manage/staff/2.png"
            },
            {
              "name": "3.png",
              "path": "img/flow/6Manage/staff/3.png"
            },
            {
              "name": "4.png",
              "path": "img/flow/6Manage/staff/4.png"
            },
            {
              "name": "5.png",
              "path": "img/flow/6Manage/staff/5.png"
            },
            {
              "name": "6.png",
              "path": "img/flow/6Manage/staff/6.png"
            },
            {
              "name": "7.png",
              "path": "img/flow/6Manage/staff/7.png"
            },
            {
              "name": "8.png",
              "path": "img/flow/6Manage/staff/8.png"
            },
            {
              "name": "9.png",
              "path": "img/flow/6Manage/staff/9.png"
            }
          ]
        }
      ],
      "files": []
    }
  ],
  "files": []
};
